config/urls.py
from django.contrib import admin
from django.urls import path,include
from pybo.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('board/', include('board.urls')),
    path('', base_views.index, name='index'),
]

pybo/urls.py
'''
파일명: urls.py
Description: pybo의 모든 URL과 view함수의 메핑 담당!
생성일 : 1/25/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
from django.urls import path
from .views import base_views, question_views, answer_views, boot_views

app_name = 'pybo'

urlpatterns = [
    #base_view
    path('',base_views.index, name='index'),   #view index로 메핑
    # pybo:detail
    path('<int:question_id>/', base_views.detail, name='detail'),  # views.py의 detail method


    #answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #pybo:answer_modify
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    #pybo:answer_delete
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),


    #question
    #pybo:qustion_create
    path('question/create/', question_views.question_create, name='question_create'),
    #pybo:qustion_modify
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    #pybo:qustion_delete
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    #boot
    #temp menu
    path('boot/menu/', boot_views.boot_menu, name='boot_menu'),
    #bootstrap template
    path('boot/list/', boot_views.boot_list, name='boot_list'),
    path('boot/reg/', boot_views.boot_reg, name='boot_reg'),
    #crawling
    path('crawling/cgv/', boot_views.crawling_cgv, name='crawling_cgv'),

]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


# 질문 Question 클래스 생성: subject, content, create_date
class Question(models.Model):
    subject = models.CharField(max_length=200)  # 글자 수 제한
    content = models.TextField()  # 글자 수 제한이 없는 경우
    create_date = models.DateTimeField()  # 날짜 + 시간

    # author필드 추가: 글쓴이
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')

    # 수정일시 추가
    modify_date = models.DateTimeField(null=True, blank=True)
    # null=True: 데이터베이스에서 null 허용, blank=True 등록할 때, validation시 빈칸을 허용하겠다는 것
    # form.is_valid() 입력값 겁증 시 값이 없어도 된다.

    # 추천인
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject


class Answer(models.Model):
    # on_delete=models.CASCADE: 답변에 연관된 질문이 삭제되면 답변도 모두 삭제하세요.
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()  # 글자수 제한이 없는
    create_date = models.DateTimeField()  # 날짜 + 시간

    # author필드 추가: 글쓴이
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')

    # 수정일시 추가
    modify_date = models.DateTimeField(null=True, blank=True)

    # 추천인
    voter = models.ManyToManyField(User, related_name='voter_answer')
    # 입력필드에 null 허용하기
    # author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)


class Board(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.IntegerField()
    modify_date = models.DateTimeField(null=True, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE)

pybo/forms.py
'''
파일명: forms.py
Description: html form 관리
생성일 : 2/1/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
from django import forms
from pybo.models import Question, Answer

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        
        fields = ['content']
        
        labels = {
            'content': '답변 내용'
        }

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question #사용할 question model

        fields = ['subject','content'] #QuestionForm에서 사용할 question model의 속성들

        labels = {
            'subject' : '제목',
            'content' : '내용',
        }

pybo/views/answer_views.py
'''
파일명: answer_views.py
Description:
생성일 : 2/8/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    '''답변: 좋아요'''
    logging.info('1.answer_vote:{}'.format(answer_id))
    answer = get_object_or_404(Answer, pk=answer_id)

    #본인 글은 추천하지 못하게
    if request.user == answer.author:
        logging.info('2.request.user:{}'.format(request.user))
        logging.info('2.anaswer.author:{}'.format(answer.author))
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    logging.info('2.question_id:{}'.format(answer.question.id))
    return redirect('{}#answer_{}'.
                    format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    logging.info('1.answer_delete:{}'.format(answer_id))
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error('삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id = answer.question.id)
    logging.info('2.right before deleteing')
    answer.delete()
    logging.info('3.deleted')

    return redirect('pybo:detail', question_id=answer.question.id)
@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    logging.info('1.answer_modify:{}'.format(answer_id))
    #1.answer id에 해당되는 데이터 조회
    #2.수정 권한 체크: 권한이 없는 경우 메시지 전달
    #3. POST: 수정
    #4. GET : 수정 Form 전달

    #1.
    answer=get_object_or_404(Answer, pk=answer_id)
    #2.
    if request.user != answer.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('pybo:detail',question_id=answer.question.id)
    #3.
    if request.method == "POST": #수정
        form = AnswerForm(request.POST, instance=answer)
        logging.info('2.answer_modify POST answer:{}'.format(answer))

        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            logging.info('3.answer_modify POST form.is_valid:{}'.format(answer))
            answer = form.save()
            #수정화면
            return redirect('{}#answer_{}'.
                            format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:                       #수정 form template
        form = AnswerForm(instance=answer)
    context = {'answer':answer, 'form':form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    '''답변 등록'''

    logging.info('answer_crete question_id:{}'.format(question_id))
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False) #content만 저장하고 확정은 하지 않음.
            answer.create_date = timezone.now()
            answer.question = question
            answer.author = request.user  # author 속성에 로그인 계정 저장

            logging.info('3.answer.author:{}'.format(answer.author))
            answer.save() #최종 저장
            return redirect('{}#answer_{}'.
                            format(resolve_url('pybo:detail',question_id = question.id), answer.id ))
    else:
        logging.info('1.else:{}')
        form = AnswerForm()

    #form validation
    context = {'question':question, 'form':form}
    return render(request,'pybo/question_detail.html', context)
    # Question과 Answer 처럼 서로 연결되어 있는 경우 연결 모델명 _set 연결데이터를 조회 할 수 있다.
    # question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    # return redirect('pybo:detail',question_id=question_id)

pybo/views/base_views.py
'''
파일명: base_views.py
Description:
생성일 : 2/8/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
import logging
logger = logging.getLogger('pybo')

from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Question


def detail(request, question_id):
    '''question 상세'''
    logging.info('1. question_id:{}'.format(question_id))
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question,pk=question_id)
    logging.info('2. question:{}'.format(question))
    context = {'question':question}
    return render(request,'pybo/question_detail.html',context)

def index(request):
    '''question 목록'''
    # Question.objects.order_by('create_date') #=>ASC
    logging.info('index 레벨로 출력')
    # print('index 레벨로 출력')
    #list order create_date desc

    #입력인자: http://127.0.0.1:8000/pybo/1

    page = request.GET.get('page','1') #페이지
    kw = request.GET.get('kw','') #검색어
    div = request.GET.get('div','') #검색어 구분
    size = request.GET.get('size','10') #페이지 사이즈

    logging.info('page:{}'.format(page))
    logging.info('kw:{}'.format(kw))
    logging.info('div:{}'.format(div))
    logging.info('size:{}'.format(size))

    question_list = Question.objects.order_by('-create_date') # order_by('-필드')=>DESC
    #subject__contains : 사용 __contains 또는 __icontains(대소문자 구분) :
    if 10 == div:
        logging.info('if 10')
        question_list = question_list.filter(subject__contains = kw)
    elif 20 == div:
        logging.info('elif 20')
        question_list = question_list.filter(content__contains = kw)
    elif 30 == div:
        logging.info('elif 30')
        #포린키 관계: author '__' username
        # author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
        question_list = question_list.filter(author__username__contains=kw)

    #paging

    paginator = Paginator(question_list, size)
    page_obj = paginator.get_page(page)

    # paginator.count: 전체 게시물 개수
    # paginator.per_oage:페이지당 보여줄 게시물 개수
    # paginator.per_range: 페이지 범위
    # number: 현재 페이지 번호
    # previous_page_number: 이전 페이지 번호
    # next_page_number: 다음 페이지 번호
    # has_previous: 이전 페이지 유무
    # has_naext: 다음 페이지 유무
    # start_index : 현재 페이지 시작 인덱스(1부터 시작)
    # end_index: 현재 페이지 끝 인덱스


    # question_list = Question.objects.filter(id=99)
    context = {'question_list':page_obj, 'kw':kw, 'page':page,'div':div}
    logging.info('question_list:{}'.format(page_obj))

    return render(request,'pybo/question_list.html',context)

pybo/views/boot_views.py
'''
파일명: boot_views.py
Description:
생성일 : 2/8/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
import requests
from bs4 import BeautifulSoup
from django.shortcuts import render


def crawling_cgv(request):
    '''CGV 무비차트'''
    url = 'http://www.cgv.co.kr/movies/?lt=1&ft=0'
    response = requests.get(url)

    if 200 == response.status_code:
        html = response.text
        # print('html:{}'.format(html))

        # box-contents
        soup = BeautifulSoup(html, 'html.parser')
        title = soup.select('div.box-contents strong.title')
        reserve = soup.select('div.score strong.percent span')
        poster = soup.select('span.thumb-image img')

        title_list=[]
        #예매율
        reserve_list = []
        poster_list = []



        # context={'title':title.getText()}

        for page in range(0, 7, 1):
            posterImg = poster[page]
            # print('posterImg:{}'.format(posterImg))
            imgUrlPath = posterImg.get('src')
            # print('imgUrlPath:{}'.format(imgUrlPath))
            title_list.append(title[page].getText())
            reserve_list.append(reserve[page].getText())
            poster_list.append(imgUrlPath)
            print('title[page]:{},{}'.format(title[page].getText()
                                             , reserve[page].getText()
                                             , imgUrlPath
                                             ))

        context = {'context':zip(title_list,reserve_list,poster_list)}

    else:
        print('접속오류 response.status_code:{}'.format(response.status_code))
    return render(request, 'pybo/crawling_cgv.html', context)

#bootstrap list
def boot_menu(request):
    '''개발에 사용되는 임시 메뉴'''
    return render(request, 'pybo/menu.html')
def boot_reg(request):
    '''bootstrap register template'''
    return render(request, 'pybo/reg.html')

def boot_list(request):
    '''bootstrap template'''
    return render(request,'pybo/list.html')

pybo/views/question_views.py
'''
파일명: question_views.py
Description:
생성일 : 2/8/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question

@login_required(login_url='common:login')
def question_vote(request, question_id):
    '''질문: 좋아요'''
    logging.info('1.question_vote:{}'.format(question_id))
    # get_object_or_404() 데이타 가져오는 것
    question = get_object_or_404(Question, pk=question_id)

    #본인 글은 추천 하지 못하게
    if request.user == question.author:
        logging.info('2.request.user:{}'.format(request.user))
        logging.info('2.question.author:{}'.format(question.author))
        messages.error(request, '본인이 작성한 글은 추천 할 수 없습니다.')
    else:
        question.voter.add(request.user)

    return redirect('pybo:detail', question_id)


    pass

@login_required(login_url='common:login') #로그인이 되어있지 않으면 login 페이지로 이동
def question_create(request):
    '''질문등록'''

    logging.info('1.request.method:{}'.format(request.method))
    if request.method == 'POST':
        logging.info('2.queston_create post')
        #저장
        form = QuestionForm(request.POST) #request.POST 데이터
        logging.info('3.queston_create post')
        if form.is_valid(): #form(질문등록)이 유효하면 등록
            logging.info('4.form.is_valid():{}'.format(form.is_valid()))
            question = form.save(commit=False) #subject, content만 저장(확정(commit)은 하지 않음.=> 날짜가 없기 때문에)
            question.create_date = timezone.now()
            question.author = request.user #author 속성에 로그인 계정 저장

            logging.info('4.question.author:{}'.format(question.author))
            question.save() #날짜까지 생성해서 저장(Commit)

            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    '''질문 수정 : login 필수'''
    logging.info('1. question_modify')
    question = get_object_or_404(Question, pk=question_id) #question id로 Question 조회

    #권한 check
    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('pybo:detail',question_id = question.id)

    if request.method == 'POST':
        logging.info('2.question_modify post')
        form = QuestionForm(request.POST, instance=question)

        if form.is_valid():
            logging.info('3.form.is_valid():{}'.format(form.is_valid()))
            question = form.save(commit=False) #질문 내용,
            question.modify_date = timezone.now() #수정일시 저장
            question.save() #수정일시까지 생성해서 저장(Commit)
            return redirect("pybo:detail", question_id = question.id)

    else:
        form = QuestionForm(instance = question) #get 수정할 데이터 전달!

    context={'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    logging.info('1.question_delete')
    logging.info('2.question_id:{}'.format(question_id))
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error('삭제 권한이 잆습니다.')
        return redirect('pybo:detail', question_id = question.id)

    question.delete() #삭제
    return redirect('pybo:index')

templates/pybo/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--    크기의 확대축소를 못하도록 제한하는 것(down-below)-->
    <meta  name="viewport" content="width=device-width,initial-scale=1.0">
    {% load static %} <!--css, js, images 로딩 최상단에 위치!-->
    <link rel="stylesheet" type="text/css" href="{%static 'style.css'%}">
    <!--Bootstrap  -->
    <link rel="stylesheet" type="text/css" href="{%static 'bootstrap.min.css' %}">
    <title>임시 메뉴</title>
</head>
<body>
    <div class="container">
        <!--제목-->
        <div class="text-start mt-3 mb-5">
            <h2>임시 메뉴</h2>
        </div>
        <!--제목 end-->
        <!--검색, 버튼-->
        <div class="d-grid gap-2 d-md-flex justify-content-end mb-3">
            <!--검색 form-->
            <form action="#" class="col-sm-11 col-md-11 col-lg-11 text-end">
                <select class="form-select-sm">
                    <option selected>전체</option>
                    <option value="10">제목</option>
                    <option value="20">내용</option>
                    <option value="30">작성자</option>
                </select>
                <input type="text" class="form-control-sm" placeholder="검색어">
                <select class="form-select-sm">
                    <option value="10">10</option>
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
            </form>
            <!--form end-->

            <!--form 안에 button을 넣지 않는 이유는 두번 조회될 경우가 생길 수 있기 때문이다.-->
            <!--button-->
            <div class="col-sm-1 col-md-1 col-lg-1 text-end">
                <input type="button" class="btn btn-primary btn-sm" value="조회">
                <input type="button" class="btn btn-primary btn-sm" value="등록">
            </div>
            <!--button end-->
        </div>
        <!--검색, 버튼 end-->
        <!--table-->
        <div class="container">
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr class="table-dark">
                        <th scope="col" class="text-center">NO.</th>
                        <th scope="col" class="text-center">메뉴</th>
                        <th scope="col" class="text-center">설명</th>
                        <th scope="col" class="text-center">완성일</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-center">1</td> <!--가운데 정렬-->
                        <td class="text-start"><a href="{% url 'pybo:index'%}">질문목록</a></td>  <!--왼쪽 정렬-->
                        <td class="text-start">질문목록</td>
                        <td class="text-center">2023-01-30</td>
                    </tr>
                    <tr>
                        <td class="text-center">2</td> <!--가운데 정렬-->
                        <td class="text-start"><a href="{% url 'pybo:boot_list'%}">boot_list</a></td>  <!--왼쪽 정렬-->
                        <td class="text-start">부트스트랩의 목록 템플릿</td>
                        <td class="text-center">2023-01-30</td>
                    </tr>
                    <tr>
                        <td class="text-center">3</td> <!--가운데 정렬-->
                        <td class="text-start"><a href="{% url 'pybo:boot_reg'%}">boot_reg</a></td>  <!--왼쪽 정렬-->
                        <td class="text-start">부트스트랩의 등록 템플릿</td>
                        <td class="text-center">2023-01-30</td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
    <!--table end-->

    <!--paging-->
    <div class="d-grid gap-2 d-md-flex justify-content-center mb-3">
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
    </div>
    <!--paging end-->


</body>
</html>

templates/pybo/question_detail.html
{%extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
  <!--container-->
    <div class="container">
        <!--질문 py:상하패딩값 -->
        <h2 class="boarder-bottom py-2">{{question.subject}}</h2>
        <div class="card">
            <!--pre-line
                연속 공백을 하나로 합침. 줄바꿈은 개행 문자와 <br> 요소에서 일어나며,
                한 줄이 너무 길어서 넘칠 경우 자동으로 줄을 바꿉니다.-->
            <!--message 표시-->
            {% if messages %}
            <div class="alert alert-danger" role="alert">
                {% for message in messages %}
                <strong>{{message.tags}}</strong>
                <ul>
                    <li>{{message.message}}</li>
                </ul>
                {% endfor %}
            </div>
            {% endif %}
            <!--message 표시 end---------------------->
            <div class="card-text" >{{question.content|mark}}</div>
            <!--수정자, 수정일-->
            {% if question.modify_date %}
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    <div class="mb-2"> 수정일: </div>
                    <div>{{question.modify_date}}</div>
                </div>
            </div>
            {% endif %}
            <!--수정자, 수정일 end-->
            <!--등록자, 등록일-->
             <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    <div class="mb-2"> 질문자: {{question.author.username}}</div>
                    <div>{{question.create_date}}</div>
                </div>
            </div>
            <!--등록자, 등록일 end-->
            <!--질문 수정 버튼-->
            <div class="my-3">
                <!--좋아요-->
                <a href="javascript:void(0);"
                   data-uri="{% url 'pybo:question_vote' question.id %}"  class="recommend btn btn-outline-primary btn-sm" >
                    좋아요 <i class="bi bi-hearts"></i> <span class="badge bg-success rounded-pill">{{question.voter.count}}</span></a>
                {% if question.author == request.user %} <!--글쓴이와 로그인한 사용자가 동일하면 -->
                <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-outline-primary btn-sm" >수정</a>
                <a href="javascript:void(0);" data-uri="{% url 'pybo:question_delete' question.id %}"  class="delete btn btn-outline-danger btn-sm" >삭제</a>
                {% endif %}
            </div>
        </div>
        <!--질문 end ----------------------------------------------------->
      <!--답변-->
      <h5 class="border-bottom py-2 my-3">{{question.answer_set.count}} 개의 답변이 있습니다.</h5>
        {%for answer in question.answer_set.all%}

        <div class="card mb-3">
            <!--pre-line
                연속 공백을 하나로 합침. 줄바꿈은 개행 문자와 <br> 요소에서 일어나며,
                한 줄이 너무 길어서 넘칠 경우 자동으로 줄을 바꿉니다.-->
            <!--answer_+answer.id-->
            <a id="answer_{{answer.id}}"></a>
            <div class="card-text" style="white-space pre-line" >{{answer.content}}</div>
             <!--수정자, 수정일-->
            {% if answer.modify_date %}
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    <div class="mb-2"> 수정일: </div>
                    <div>{{answer.modify_date}}</div>
                </div>
            </div>
            {% endif %}
            <!--수정자, 수정일 end-->
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    <div class="mb-2">답변자: {{answer.author.username}}</div>
                    <div>{{answer.create_date}}</div>
                </div>
            </div>

            <!--답변 수정 버튼-->

            <div class="my-3">
                <!--좋아요-->
                 <a href="javascript:void(0);"
                   data-uri="{% url 'pybo:answer_vote' answer.id %}"  class="recommend btn btn-outline-primary btn-sm" >
                    좋아요 <i class="bi bi-hearts"></i> <span class="badge bg-success rounded-pill">{{answer.voter.count}}</span></a>
                {% if answer.author == request.user %}
                <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-warning">수정</a>
                <a href="#" data-uri="{% url 'pybo:answer_delete' answer.id %}" class="delete btn btn-outline-danger btn-sm">삭제</a>
                {% endif %}
            </div>

        </div>
        {% endfor %}
        <!--답변 end-------------------------------------------------------->
        <!--답변 등록-->
        <form action="{%url 'pybo:answer_create' question.id %}" method="POST" class="my-3" name="answer_frm">
            {% csrf_token %}
            {% include "form_error.html" %}

            <div class="mb-3">
                <label for="content" class="col-form-label">내용</label>
                <textarea rows="10" cols="20" class="form-control" name="content" id="content"></textarea>
            </div>
            <input type="submit" name="submit-btn" class="btn btn-primary btn-sm" value="답변 등록">
        </form>
<!--             <input type="button" class="btn btn-primary btn-sm" value="답변 등록" onclick="javascript:doSave();">-->
        <!--답변 등록 end--------------------------------------------------->
    </div>
    <!--container end------------------------------------------------------>

    {% endblock %}
    {% block script%}
    <script>
        //삭제: getElementsByClassName 'delete' 클래스 이름으로 element 찾기
        //Array.from() 메서드는 유사 배열 객체(array-like object)나
        //반복 가능한 객체(iterable object)를 얕게 복사해 새로운Array 객체를 만듭니다.
        //const delete_elements = document.querySelectorAll(".delete")

       //DELETE button
        const delete_elements = document.getElementsByClassName('delete');
        Array.from(delete_elements).forEach(function(element){
            element.addEventListener('click',function(){
                console.log('delete click');
                if(confirm('삭제 하시겠습니까?')){
                    console.log('삭제하시겠습니까?');
                    //url호출
                    console.log('this.dataset.uri:'+this.dataset.uri);
                    location.href = this.dataset.uri;
                }
            });
        });

        //question:좋아요
        const recommend_elements = document.querySelectorAll(".recommend");
        Array.from(recommend_elements).forEach(function(element){
            element.addEventListener('click', function(){
                console.log('recommend click')
                if (confirm('추천하시겠습니까?')){
                    console.log('recommend?');
                    //url호출
                    console.log('this.dataset.uri:'+this.dataset.uri);
                    location.href = this.dataset.uri;
                }
            })
        })

    </script>
    {% endblock %}