board/urls.py
'''
파일명: urls.py
Description:
생성일 : 2/15/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
from django.urls import path

from . import views
from .views import board_list

app_name = 'board'

urlpatterns = [
    path('list/', views.board_list, name='board_list'),
    path('board_create/', views.board_create, name='board_create'),
    path('board_detail/<int:board_id>/', views.board_detail, name='board_detail'),
    path('board_modify/<int:board_id>/', views.board_modify, name='board_modify'),
    path('board_delete/<int:board_id>/', views.board_delete, name='board_delete'),
]

common/urls.py
'''
파일명: urls.py
Description: 로그인/로그 아웃 구현
생성일 : 2/6/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name='common'

urlpatterns = [
    #django.contrib.auth앱의 LoginView 클래스를 활용
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    #logout
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/',views.signup,name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from pybo.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('board/', include('board.urls')),
    path('', base_views.index, name='index'),
]

pybo/urls.py
'''
파일명: urls.py
Description: pybo의 모든 URL과 view함수의 메핑 담당!
생성일 : 1/25/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
from django.urls import path
from .views import base_views, question_views, answer_views, boot_views

app_name = 'pybo'

urlpatterns = [
    #base_view
    path('',base_views.index, name='index'),   #view index로 메핑
    # pybo:detail
    path('<int:question_id>/', base_views.detail, name='detail'),  # views.py의 detail method


    #answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #pybo:answer_modify
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    #pybo:answer_delete
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),


    #question
    #pybo:qustion_create
    path('question/create/', question_views.question_create, name='question_create'),
    #pybo:qustion_modify
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    #pybo:qustion_delete
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    #boot
    #temp menu
    path('boot/menu/', boot_views.boot_menu, name='boot_menu'),
    #bootstrap template
    path('boot/list/', boot_views.boot_list, name='boot_list'),
    path('boot/reg/', boot_views.boot_reg, name='boot_reg'),
    #crawling
    path('crawling/cgv/', boot_views.crawling_cgv, name='crawling_cgv'),

]

pybo/views/base_views.py
'''
파일명: base_views.py
Description:
생성일 : 2/8/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
import logging
logger = logging.getLogger('pybo')

from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from ..models import Question


def detail(request, question_id):
    '''question 상세'''
    logging.info('1. question_id:{}'.format(question_id))
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question,pk=question_id)
    logging.info('2. question:{}'.format(question))
    context = {'question':question}
    return render(request,'pybo/question_detail.html',context)

def index(request):
    '''question 목록'''
    # Question.objects.order_by('create_date') #=>ASC
    logging.info('index 레벨로 출력')
    # print('index 레벨로 출력')
    #list order create_date desc

    #입력인자: http://127.0.0.1:8000/pybo/1

    page = request.GET.get('page','1') #페이지
    kw = request.GET.get('kw','') #검색어
    div = request.GET.get('div','') #검색어 구분
    size = request.GET.get('size','10') #페이지 사이즈

    logging.info('page:{}'.format(page))
    logging.info('kw:{}'.format(kw))
    logging.info('div:{}'.format(div))
    logging.info('size:{}'.format(size))

    question_list = Question.objects.order_by('-create_date') # order_by('-필드')=>DESC
    #subject__contains : 사용 __contains 또는 __icontains(대소문자 구분) :
    if 10 == div:
        logging.info('if 10')
        question_list = question_list.filter(subject__contains = kw)
    elif 20 == div:
        logging.info('elif 20')
        question_list = question_list.filter(content__contains = kw)
    elif 30 == div:
        logging.info('elif 30')
        #포린키 관계: author '__' username
        # author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
        question_list = question_list.filter(author__username__contains=kw)

    #paging

    paginator = Paginator(question_list, size)
    page_obj = paginator.get_page(page)

    # paginator.count: 전체 게시물 개수
    # paginator.per_oage:페이지당 보여줄 게시물 개수
    # paginator.per_range: 페이지 범위
    # number: 현재 페이지 번호
    # previous_page_number: 이전 페이지 번호
    # next_page_number: 다음 페이지 번호
    # has_previous: 이전 페이지 유무
    # has_naext: 다음 페이지 유무
    # start_index : 현재 페이지 시작 인덱스(1부터 시작)
    # end_index: 현재 페이지 끝 인덱스


    # question_list = Question.objects.filter(id=99)
    context = {'question_list':page_obj, 'kw':kw, 'page':page,'div':div}
    logging.info('question_list:{}'.format(page_obj))

    return render(request,'pybo/question_list.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--FAVICON-->
    <link rel="shortcut icon" type="image/x-icon" href= "{%static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{%static 'style.css'%}">
     <!--Bootstrap  -->
    <link rel="stylesheet" type="text/css" href="{%static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <script src="{% static 'common.js' %}"></script>
    <title>Pybo</title>
</head>
<body>
    <!--네비게이션 바-->
    {% include 'navbar.html' %}
    <!--네비게이션바 end------------------------------------------------------------->
  <!--기본 템플릿 안에 삽입될 내용 -->
      {% block content %}
      {% endblock%}
  <!--기본 템플릿 안에 삽입될 내용 end ------------------------------------------ -->
 <script src="{% static bootstrap.min.js %}"></script>
    <!--javascript start-->
    {% block script %}
    {% endblock %}
    <!--javascript end-->
</body>
</html>

templates/form_error.html
<!--form validation 기능-->
{% if form.errors %}
<div class="alert alert-warning" role="alert">
    {% for field in form%}
        {%if field.errors %}
            <div><strong>{{field.label}}</strong></div>
            {{field.errors}}
        {% endif %}
    {% endfor %}

</div>
{% endif %}
<!--form validation 기능 end--------------------------------------------------------->

templates/navbar.html
<!--네비게이션바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <!--로그인-->
            <li class="nav-item">
                <!--로그인 정보가 있는 경우-->
                {% if user.is_authenticated %} <!--로그인 상태라면, is_anonymous: 로그아웃 상태라면-->
                <a class="nav-link active" aria-current="page"
                   href="{% url 'common:logout' %}">{{user.username}}
                    <i class="bi bi-box-arrow-right"></i>
                </a> <!--username:사용자명   {{user.is_superuser}}-->
                {% else %}
                <a class="nav-link active" aria-current="page"
                   href="{% url 'common:login' %}">로그인
                    <i class="bi bi-box-arrow-in-right"></i>
                </a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page"
                    href="#">
                    <i class="bi bi-instagram"></i>
                </a>
            </li>
            <!--회원가입-->
            <li class="nav-item">
                {% if not user.is_authenticated %}
                  <a class="nav-link active" aria-current="page"
                   href="{% url 'common:signup' %}">회원가입</a>
                {% endif %}
            </li>
        </ul>
    </div>
    <div class="collapse navbar-collapse" >
         <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'board:board_list'%}">게시판</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'pybo:index'%}">질문목록</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'pybo:boot_list'%}">boot_list</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'pybo:boot_reg'%}">boot_reg</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'pybo:crawling_cgv'%}">무비차트</a>
                </li>

            </ul>
    </div>



</nav>
<!--네비게이션바 end-------------------------------------------------------------->