board/urls.py
'''
파일명: urls.py
Description:
생성일 : 2/15/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
from django.urls import path

from . import views
from .views import board_list

app_name = 'board'

urlpatterns = [
    path('list/', views.board_list, name='board_list'),
    path('board_create/', views.board_create, name='board_create'),
    path('board_detail/<int:board_id>/', views.board_detail, name='board_detail'),
    path('board_modify/<int:board_id>/', views.board_modify, name='board_modify'),
    path('board_delete/<int:board_id>/', views.board_delete, name='board_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from pybo.views import base_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('board/', include('board.urls')),
    path('', base_views.index, name='index'),
]

pybo/urls.py
'''
파일명: urls.py
Description: pybo의 모든 URL과 view함수의 메핑 담당!
생성일 : 1/25/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
from django.urls import path
from .views import base_views, question_views, answer_views, boot_views

app_name = 'pybo'

urlpatterns = [
    #base_view
    path('',base_views.index, name='index'),   #view index로 메핑
    # pybo:detail
    path('<int:question_id>/', base_views.detail, name='detail'),  # views.py의 detail method


    #answer
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    #pybo:answer_modify
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    #pybo:answer_delete
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),


    #question
    #pybo:qustion_create
    path('question/create/', question_views.question_create, name='question_create'),
    #pybo:qustion_modify
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    #pybo:qustion_delete
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    #boot
    #temp menu
    path('boot/menu/', boot_views.boot_menu, name='boot_menu'),
    #bootstrap template
    path('boot/list/', boot_views.boot_list, name='boot_list'),
    path('boot/reg/', boot_views.boot_reg, name='boot_reg'),
    #crawling
    path('crawling/cgv/', boot_views.crawling_cgv, name='crawling_cgv'),

]

board/forms.py
'''
파일명: forms.py
Description:
생성일 : 2/15/2023
생성자: oyunm
since 2023.01.09 Copyright (C) by YoungCheon All right reserved.
'''
from django import forms

from pybo.models import Board


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board

        fields = ['subject','content']

        labels = {
            'subject' : '제목',
            'content' : '내용',
        }

board/views.py
import logging

from django.contrib import messages
from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from board.forms import BoardForm
from pybo.models import Board

@login_required(login_url='common:login')
def board_delete(request, board_id):
    '''게시물 삭제'''
    logging.info('1.board_delete')
    logging.info('2.board_id:{}'.format(board_id))
    board = get_object_or_404(Board, pk=board_id)

    if request.user != board.author:
        messages.error('삭제 권한이 없습니다.')
        return redirect('board:board_detail', board_id=board.id)

    board.delete()
    return redirect('board:board_list')

@login_required(login_url='common:login')
def board_modify(request, board_id):
    '''게시물 수정'''
    logging.info('1.board_modify')
    board = get_object_or_404(Board,pk=board_id)

    if request.user != board.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('board:board_detail', board_id = board.id)
    if request.method == 'POST':
        logging.info('2.question_modify post')
        form = BoardForm(request.POST, instance=board)

        if form.is_valid():
            logging.info('3.form.is_valid:{}'.format(form.is_valid()))
            board = form.save(commit=False)
            board.modify_date = timezone.now()
            board.save()
            return redirect("board:board_detail",board_id=board.id)
    else:
        form = BoardForm(instance=board)
    context = {'form':form}
    return render(request, 'board/board_form.html', context)

def board_detail(request, board_id):
    '''게시물 상세'''
    logging.info('1.board_id:{}'.format(board_id))
    board = get_object_or_404(Board, pk=board_id)

    logging.info('2.board:{}'.format(board))
    context = {'board': board}
    return render(request, 'board/board_detail.html', context)

@login_required(login_url='common:login')
def board_create(request):
    '''게시물 등록'''
    logging.info('1.request.method:{}'.format(request.method))
    if request.method == 'POST':
        logging.info('2.board_create post')
        form = BoardForm(request.POST)
        logging.info('3.board_create post')
        if form.is_valid():
            logging.info('4.form.is_valid():{}'.format(form.is_valid()))
            board = form.save(commit=False)
            board.create_date = timezone.now()
            board.author = request.user

            logging.info('4.board.author:{}'.format(board.author))

            board.save()
            return redirect("board:board_list")
    else:
        form = BoardForm()
    context = {'form':form}
    return render(request, 'board/board_form.html', context)



# Create your views here.
def board_list(request):
    '''board 목록'''
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    div = request.GET.get('div', '')
    size = request.GET.get('size', '10')

    logging.info('page:{}'.format(page))
    logging.info('kw:{}'.format(kw))
    logging.info('div:{}'.format(div))
    logging.info('size:{}'.format(size))

    board_list = Board.objects.order_by('-create_date')

    if '10' == div:
        logging.info('if 10')
        board_list = board_list.filter(subject_contains=kw)
    elif '20' == div:
        logging.info('elif 20')
        board_list = board_list.filter(content_contains=kw)
    elif '30' == div:
        logging.info('elif 30')
        question_list = board_list.filter(author__username__contains=kw)

    paginator = Paginator(board_list, size)
    page_obj = paginator.get_page(page)

    context = {'board_list': page_obj, 'kw': kw, 'page':page, 'div': div, 'size':size}
    logging.info('board_list:{}'.format(page_obj))

    return render(request, 'board/list.html', context)

templates/board/board_detail.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<!--container-->
<div class="container">
    <!--제목-->
    <h2 class="boarder-bottom py-2">{{board.subject}}</h2>
    <!--제목 end-->
    <div class="card my-3">
        <!--,essage 표시-->
        {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
            <strong>{{message.tags}}</strong>
            <ul>
                <li>
                    {{message.message}}
                </li>
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!--message 표시 end-->
        <div class="card-text">{{board.content|mark}}</div>
        <div class="d-flex justify-content-end">
            <!--수정자, 수정일-->
            {% if board.modify_date %}
            <div class="badge bg-light text-dark p-2 text-start mx-3">
                <div class="mb-2">수정일</div>
                <div>{{board.modify_date}}</div>
            </div>
            {% endif %}
            <!--수정자, 수정일 end----------->
            <!--등록자, 등록일-->
            <div class="badge bg-light text-dark p-2 text-start">
                <div class="mb-2">{{board.author.username}}</div>
                <div>{{board.create_date}}</div>
            </div>
            <!--등록자, 등록일 end--------->
        </div>
        <!--질문 수정-->
        <div class="my-3">
            {% if board.author == request.user%}
            <a href="{% url 'board:board_modify' board.id %}" class="btn btn-sm btn-outline-success">수정</a>
            <a href="javascript:void(0);" data-uri="{% url 'board:board_delete' board.id %}" class="delete btn btn-sm btn-outline-danger">삭제</a>
            {% endif %}
        </div>
    </div>
</div>
<!--container end----------->

{% endblock %}
{% block script %}
    <script>
        const delete_elements = document.querySelectorAll(".delete");
        Array.from(delete_elements).forEach(function(element){
            element.addEventListener('click',function(){
                console.log('delete click');
                if(confirm('삭제 하시겠습니까?')){
                    console.log('삭제하시겠습니까?');
                    console.log('this.dataset.uri:'+this.dataset.uri);
                    location.href = this.dataset.uri;
                }
            });
        });
    </script>
{% endblock %}

templates/board/board_form.html
{% extends 'base.html' %}
{% block content %}
    <!--container-->
    <div class="container">
        <!--제목-->
        <div class="text-start mb-5">
            <h2>게시물 등록</h2>
        </div>
        <!--제목 end----------->
        <!--form starts-->
        <form method="post" class="post-form m-3">
            {% csrf_token %}
            <!--form validation 기능-->
            {% include 'form_error.html' %}
            <!--form validation 기능 end---->

            <div class="mb-3">
                <label for="subject" class="col-form-label">제목</label>
                <div class="">
                    <input type="text" class="form-control" id="subject" name="subject" value="{{form.subject.value|default_if_none:''}}">
                </div>
            </div>
            <div>
                <label for="content" class="col-form-label">내용</label>
                <div>
                    <textarea rows="10" class="form-control" name="content" id="content">{{form.content.value|default_if_none:''}}</textarea>
                </div>
            </div>

            <button type="submit" class="btn btn-primary btn-sm">저장</button>
        </form>
        <!--form ends-->
    </div>
    <!--container end----------------->
{% endblock %}

templates/board/list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}
<!--container-->
<div class="container">
    <!--제목-->
    <div class="text-start mb-5">
        <h2>게시판</h2>
    </div>
        <!--검색,버튼-->
    <div class="d-grid gap-2 d-md-flex justify-content-end">
         <div class="text-end my-1">
            <select class="form-select-sm"  id="search_div" >
              <option selected value="">전체</option>
              <option value="10" {% if '10' == div %} selected {% endif %} >제목</option>
              <option value="20" {% if '20' == div %} selected {% endif %} >내용</option>
              <option value="30" {% if '30' == div %} selected {% endif %} >작성자</option>
            </select>
            <input type="text" class="form-control-sm" id="search_kw" value="{{ kw | default_if_none:''}}"  placeholder="검색어">
            <select class="form-select-sm" id="page_size" >
              <option value="10" {% if '10' == size %} selected {% endif %} >10</option>
              <option value="20" {% if '20' == size %} selected {% endif %} >20</option>
              <option value="30" {% if '30' == size %} selected {% endif %} >30</option>
              <option value="50" {% if '50' == size %} selected {% endif %} >50</option>
              <option value="100" {% if '100' == size %} selected {% endif %} >100</option>
            </select>
        </div>

        <div class="text-end my-1">
            <button class="btn btn-primary btn-sm" id="btn_search">조회</button>
            <a href="{% url 'board:board_create' %}" class="btn btn-primary btn-sm">등록</a>
        </div>
    </div>
    <!--제목 end--------------->

    <table class="table table-striped table-hover table-bordered table-sm">
        <thead>
            <tr class="table-dark">
                <th scope="col" class="text-center">NO.</th>
                <th scope="col" class="text-center" style="width: 50%;">제목</th>
                <th scope="col" class="text-center">글쓴이</th>
                <th scope="col" class="text-center">작성일</th>
            </tr>
        </thead>
        <tbody>
        {% if board_list %}
            {% for board in board_list %}
                <tr>
                    <td class="text-center">{{ board_list.paginator.count| sub:board_list.start_index|sub:forloop.counter0|add:1 }}</td>
                    <td class="text-start">
                        <a href="{% url 'board:board_detail' board.id %}">{{board.subject}}</a>
                    </td>
                    <td class="text-center">{{board.author.username}}</td>
                    <td class="text-center">{{board.create_date|date:"Y-m-d"}}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td coldspan="99">게시물이 없습니다.</td>
            </tr>
        {% endif %}
        </tbody>
    </table>
    {% csrf_token %}

    <!--페이징 처리-->
    <ul class="pagination justify-content-center">
        <!--이전 페이지-->
        {% if board_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{board_list.previous_page_number}}" href="javascript:(0)">&laquo;</a>
        </li>
        {% else %}
        <li class="page-itm disabled">
            <a class="page-link" aria-disabled="true" href="#">&laquo;</a>
        </li>
        {% endif %}
        <!--이전 페이지 end-->

        <!--페이지 리스트 paginator.page_range-->
        {% for page_number in board_list.paginator.page_range %}
        {% if page_number >= board_list.number|add:-5 and page_number <= board_list.number|add:5 %}
        {% if page_number == board_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{page_number}}" href="javascript:void(0)">{{page_number}}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{page_number}}" href="javascript:void(0)">{{page_number}}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!--페이지 리스트 end-->

        <!--다음 페이지-->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{board_list.next_page_number}}" href="javascript:void(0);">
                &raquo;
            </a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0);">&raquo;</a>
        </li>
        {% endif %}
        <!--다음 페이지 end----->
    </ul>
    <!--페이징 처리 end-------------->
</div>
<!--container end-------------->
<form method="get" id="searchForm" action="{% url 'index' %}">
    <input type="hidden" name="kw" id="kw" value="{{kw | default_if_none:''}}">
    <input type="hidden" name="page" id="page" value="{{page}}">
    <input type="hidden" name="div" id="div" value="{{div | default_if_none:''}}">
    <input type="hidden" name="size" id="size" value="{{size}}">
</form>

{% endblock %}

{% block script %}
    <script>
        //page-link class
            const page_elements = document.querySelectorAll(".page-link");
            Array.from(page_elements).forEach(function(element){
                element.addEventListener('click',function(){
                    //console.log('page-link class');
                    //console.log('this.dataset.page:'+this.dataset.page);
                    //document.querySelector('#page').value = this.dataset.page;
                    doRetrieve(this.dataset.page);
                });
            });

            function doRetrieve(page){
                document.querySelector('#kw').value   = document.querySelector('#search_kw').value;
                document.querySelector('#page').value = page; //조회은 페이지 번호 무조건 1
                document.querySelector('#div').value = document.querySelector('#search_div').value; //조회은 페이지 번호 무조건 1
                document.querySelector('#size').value = document.querySelector('#page_size').value; //페이지 사이즈 조회
                console.log('kw:'+document.querySelector('#kw').value);
                console.log('page:'+document.querySelector('#page').value);
                console.log('div:'+document.querySelector('#div').value);
                console.log('size:'+document.querySelector('#size').value);
                document.querySelector('#searchForm').submit();
            }

            const search_kw = document.querySelector("#search_kw");
            search_kw.addEventListener("keyup",function(event){
                console.log('search_kw:'+event.keyCode );
                if( event.keyCode == 13 ){ //Enter
                    doRetrieve(1);
                }
            });

            //btn_search : 검색어, page를  searchForm할당
            const btn_search = document.querySelector("#btn_search");
            btn_search.addEventListener('click',function(){
                console.log('btn_search');
                doRetrieve(1);
            });
    </script>
{% endblock %}